### PR TITLE
feat: add title property to inputs in hierarchy JSON and shorten IDs to canonical names

### PR DESCRIPTION
**Pull request by lemilonkh**

### CODE REVIEW

**Comment by thehighestprimenumber** [comment]
Do we need to make any updates to the translation files?

**Comment by lemilonkh** [comment]
@thehighestprimenumber  No, we would need to use the title field if this is merged.
This is paused for now though and we will handle the remapping in the formulas on Evan's request.

**Comment by lemilonkh** [comment]
Closing this because of concern for too many breaking changes from the team.
Let's revisit it when we're refactoring our data model.

**Comment by lemilonkh** [comment]
Closing this because of concern for too many breaking changes from the team.
Let's revisit it when we're refactoring our data model.

**Pull request closed without merging**
