### PR TITLE
fix:adding_missing_columns

### PR DESCRIPTION
**Pull request by mfonsecaOEF**
this PR contains:
- new migration file that includes emission_factor_value and emission_factor_units columns in `country_code` table

### CODE REVIEW

**Review by lemilonkh — APPROVED** [review]

**Comment by evanp** [comment]
The migration failed when upgrading to test today. When I checked, I could see that this code just wouldn't work; it uses `alter_column` for columns it's trying to add.

I don't think non-working code should get through PRs. That's kind of why we have PRs.

@mfonsecaOEF before making a pull request, you have to at least run the code. With migrations, I'd like to know that you ran the upgrade _and_ the downgrade. Can you schedule a pairs programming session with me so we can practice writing migrations? It would be nice to include @amanda-eames so we can make sure we're doing things right.

@lemilonkh should the reviewer run migrations code forward and backwards at least once? Or should we run migrations in the GitHub actions, to automate the testing?

**Comment by lemilonkh** [comment]
I thought the reason it's using alter column is to make the columns nullable, and the PR title was just wrong? @mfonsecaOEF 

I'll revert the merge.

**Comment by amanda-eames** [comment]
If we are reverting this change then I won't approve #448 the loading scipts require the additional columns.

**Comment by lemilonkh** [comment]
I've reverted the merge of this PR as it was unfinished. @mfonsecaOEF please create the new columns properly and create another PR.

**Comment by evanp** [comment]
I fixed the problem in `develop`. The code is working now.

**Pull request merged**
