### PR TITLE
Implement translations for data source seeder/ data catalogue route

### PR DESCRIPTION
**Pull request by mfonsecaOEF**
This PR contains:
- yaml file with the translations in `en` and `es` for different columns in the datasource table
- migration file with change of text type to jsonb type for those columns

### CODE REVIEW

**Review by amanda-eames — COMMENTED** [review]
database testing passed @lemilonkh is there anything required on your end if the datatypes change from text to jsonb, if not we can approve.

**Comment by mfonsecaOEF** [comment]
> database testing passed @lemilonkh is there anything required on your end if the datatypes change from text to jsonb, if not we can approve.

**Comment by mfonsecaOEF** [comment]
@lemilonkh I changed the format of the file, csv to yaml.
Please LMK if I need to add something else to this PR

**Comment by lemilonkh** [comment]
@mfonsecaOEF is the data catalogue route updated to handle these new data types? Did you test it?

**Comment by lemilonkh** [comment]
@mfonsecaOEF let's make sure the `v0` endpoints return only the English strings, and add a v1 of the endpoint that returns `{ "en": "Name", "es": "Nombre", ... }` for every translatable string (that will be shown to the end user, so no formula identifiers etc.).

**Review by lemilonkh — APPROVED** [review]
Great, that should keep it compatible with the current CityCatalyst version! :sparkles:

**Pull request merged**
